# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Help Center"
email: jay@jaygreentree.com
description: "Simple and flexible Jekyll theme for help center."
baseurl: "/"
url: "http://jaygreentree.com/"
twitter_username: "JayTheITGuy1983"
github_username:  "jaygreentree"
color_theme:  "#013852"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
